# Generated by Django 3.0.11 on 2021-03-15 08:42

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=users.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
