# Generated by Django 3.0.11 on 2021-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20210320_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='top_offer',
            field=models.BooleanField(default=False),
        ),
    ]
