# Generated by Django 3.0.11 on 2021-02-28 20:10

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=partners.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='partner',
            name='addresses',
        ),
        migrations.AddField(
            model_name='partner',
            name='addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
